name: Build and Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21098
          local_path: './dist/*'
          remote_path: '/home/lmucunal/public_html'
          args: '-o StrictHostKeyChecking=no -o PubkeyAcceptedKeyTypes=+ssh-ed25519'
